# NumPy 

NumPy is a Library for scientific computing in Python

https://numpy.org/doc/stable/user/absolute_beginners.html

In [18]:
import numpy as np

# Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

In [3]:
#Creating sample array
arr = np.arange(0, 11)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
#Get a value at an index
arr[8]

8

In [5]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

# Broadcasting

In [6]:
#Setting a value with index range (Broadcasting)

arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr = np.arange(0, 11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
slice_arr = arr[0:6]

slice_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
slice_arr[:] = 99

slice_arr

array([99, 99, 99, 99, 99, 99])

In [10]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [11]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing

In [24]:
a = np.array(([0, 1], [2, 3]))

print(a)

print(a.shape)

[[0 1]
 [2 3]]
(2, 2)


In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d.shape

(3, 3)

In [14]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
a.shape

(3, 4)